language: python
python:
  - "3.6"
before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - export PYTHONWARNINGS="ignore::DeprecationWarning"
  - cd src/ && bash tasks/lint.sh
  - pipenv run pytest --cov=
after_success:
  - codecov
  - coveralls
  
