language: python
dist: xenial # for python 3.7
python:
  - "3.6"
  - "3.7"
before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
  - pip install codecov
script:
  - pytest --cov=src/
after_success:
  - codecov
  - coveralls
  
