language: python
python:
  - "3.6"
before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
  - pip install codecov
  - pip install bandit
script:
  - pytest --cov=src/
  - bandit -r src
after_success:
  - codecov
  - coveralls
  
