language: python
python:
  - "3.6"
before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - export PYTHONWARNINGS="ignore::DeprecationWarning"
  - bash src/tasks/lint.sh
  - pytest --cov=src/
after_success:
  - codecov
  - coveralls
  
